agent_name: governatooorr
author: valory
version: 0.1.0
license: Apache-2.0
description: The governatooorr agent.
aea_version: '>=1.19.0, <2.0.0'
fingerprint:
  __init__.py: bafybeiguw4i7zplzdw65vdyrtj25rys2hifrzsnt57p32xtrzyzh2l77di
  tests/__init__.py: bafybeihiyimopudltfy4riab6ariq2ktn6w2fqv77vd5t7k4xr7tlkthya
  tests/helpers/__init__.py: bafybeif7verbag26h6i35gr5rlatxl7veq4drup5ykwdvhgtussf2jreei
  tests/helpers/constants.py: bafybeibbokz7gzdlubnjwxrmh4tqckc7j75hfy3ae6l5a63mrbd4hp6l7u
  tests/helpers/data/json_server/data.json: bafybeics26yd33ng22lhzb3had4eevbfkfdj2jbp3qhvjpygwhkwlzhrq4
  tests/helpers/docker.py: bafybeibbi6m47mzsl43bmix4k7o7oyekzhzsljuf3dkwk23bfns6k7odkm
  tests/helpers/fixtures.py: bafybeiarm4ezp54po7nv5m4e2w3eghetma5xymnzgoovvdwh7hp2lcitqu
fingerprint_ignore_patterns: []
connections:
- fetchai/http_server:0.22.0:bafybeihp5umafxzx45aad5pj7s3343se2wjkgnbirt4pybrape22swm6de
- valory/abci:0.1.0:bafybeic6beo7cpd2qtotntlbmsrs3qfn7fw5eh2vkav6milat6awao46pu
- valory/http_client:0.23.0:bafybeieoeuy4brzimtnubmokwirhrx27ezls6cdnl5qik4rkykfle3nn2y
- valory/ledger:0.19.0:bafybeiejc7g7ebv3cleiqb4f4h4pspcu6vtr54332szwlqiabfs3sfdh44
- valory/openai:0.1.0:bafybeifq7khwp42btuiulw2fdnr5wnf5uqimnclswzyk3bneunrimwaamm
- valory/p2p_libp2p_client:0.1.0:bafybeihdnfdth3qgltefgrem7xyi4b3ejzaz67xglm2hbma2rfvpl2annq
contracts:
- valory/delegate:0.1.0:bafybeieqjhcoyuvyaluqxkuyr7jt6la7lkjjz6ntex6urru4tfa6chkcme
- valory/gnosis_safe:0.1.0:bafybeibhezhwgi5ustv675gfohsq5l5xjijp36gqueuicyl2ofrtkrortm
- valory/gnosis_safe_proxy_factory:0.1.0:bafybeiesdz7xfijeomjpps3e5k3zspvisx2xje6yqub6hzj4uczr7q33wq
- valory/sign_message_lib:0.1.0:bafybeic6y2kclcjgbel4hbr3devww7hmax44x6sx5lmnu2gpn3pvwldxlu
protocols:
- open_aea/signing:1.0.0:bafybeifuxs7gdg2okbn7uofymenjlmnih2wxwkym44lsgwmklgwuckxm2m
- valory/abci:0.1.0:bafybeigootsvqpk6th5xpdtzanxum3earifrrezfyhylfrit7yvqdrtgpe
- valory/acn:1.1.0:bafybeiapa5ilsobggnspoqhspftwolrx52udrwmaxdxgrk26heuvl4oooa
- valory/contract_api:1.0.0:bafybeiasywsvax45qmugus5kxogejj66c5taen27h4voriodz7rgushtqa
- valory/http:1.0.0:bafybeia5bxdua2i6chw6pg47bvoljzcpuqxzy4rdrorbdmcbnwmnfdobtu
- valory/ipfs:0.1.0:bafybeibjzhsengtxfofqpxy6syamplevp35obemwfp4c5lhag3v2bvgysa
- valory/ledger_api:1.0.0:bafybeigsvceac33asd6ecbqev34meyyjwu3rangenv6xp5rkxyz4krvcby
- valory/llm:1.0.0:bafybeicb4fmd2ravxzypvjllfg2uwp7plyctjtgeychk3wksz4t3ziqx3i
- valory/tendermint:0.1.0:bafybeidjqmwvgi4rqgp65tbkhmi45fwn2odr5ecezw6q47hwitsgyw4jpa
skills:
- valory/abstract_abci:0.1.0:bafybeih3bwx5apteinnoxts7sqmjlskntdbo7vvnmdbs5noo2pv76by7fu
- valory/abstract_round_abci:0.1.0:bafybeibqpzbklnljvtc67yon4ciijxj75d7vazm7rurcvbbfnk6jtudukm
- valory/governatooorr_abci:0.1.0:bafybeih4ovntqe6clnchb6prtb2fd26kpguzoyzfim6azjscxpylieljf4
- valory/proposal_collector_abci:0.1.0:bafybeiclifwftkkn7hzeluxs5q5ndvbcdvj5vln5qdo2c7u6ng6dikpq6u
- valory/proposal_voter_abci:0.1.0:bafybeigs47ozocqu4rgemik5a32m7wyxzflcew7yid3shadejyutvuentu
- valory/registration_abci:0.1.0:bafybeia25gpusnkakb2dp4heqkwtuftbc2apppq3i4bds6sphltsovgzvi
- valory/reset_pause_abci:0.1.0:bafybeigzvwbzktclahjbsyiwqnj6poree4iveon5pric6s5ixb6wrhkdhq
- valory/termination_abci:0.1.0:bafybeibcdgnarxyyqexncpfewcemraryywtwueuv7qthsjuean5l77lp2e
- valory/transaction_settlement_abci:0.1.0:bafybeiepus7qsa47gt7dyk32gaqsoae6whjoxfnplttulxrvmcauyerrdm
- valory/ceramic_read_abci:0.1.0:bafybeib36m6fi5swu43s3amtbk7w5rfie2gvzgw3xhxd7yfnka4kpcegme
- valory/ceramic_write_abci:0.1.0:bafybeifdjb2iisvtgwo44xoddhrbgqehbis6tbjdktuhh6ehwm5bnuee74
default_ledger: ethereum
required_ledgers:
- ethereum
- cosmos
default_routing: {}
connection_private_key_paths: {}
private_key_paths: {}
logging_config:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '[%(asctime)s] [%(levelname)s] %(message)s'
  handlers:
    logfile:
      class: logging.FileHandler
      formatter: standard
      filename: ${LOG_FILE:str:log.txt}
      level: INFO
    console:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stdout
  loggers:
    aea:
      handlers:
      - logfile
      - console
      propagate: false
skill_exception_policy: stop_and_exit
dependencies:
  open-aea-ledger-ethereum:
    version: ==1.37.0
default_connection: null
---
public_id: valory/abci:0.1.0
type: connection
config:
  target_skill_id: valory/governatooorr_abci:0.1.0
  host: ${str:localhost}
  port: ${int:26658}
  use_tendermint: ${bool:false}
---
public_id: valory/ledger:0.19.0
type: connection
config:
  ledger_apis:
    ethereum:
      address: ${str:http://localhost:8545}
      chain_id: ${int:1}
      poa_chain: ${bool:false}
      default_gas_price_strategy: ${str:eip1559}
---
public_id: valory/openai:0.1.0
type: connection
config:
  engine: ${str:text-davinci-003}
  max_tokens: ${int:500}
  openai_api_key: ${str:null}
  temperature: ${float:0.7}
---
public_id: valory/p2p_libp2p_client:0.1.0
type: connection
config:
  nodes:
  - uri: ${str:acn.staging.autonolas.tech:9005}
    public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
cert_requests:
- identifier: acn
  ledger_id: ethereum
  message_format: '{public_key}'
  not_after: '2023-01-01'
  not_before: '2022-01-01'
  public_key: ${str:02d3a830c9d6ea1ae91936951430dee11f4662f33118b02190693be835359a9d77}
  save_path: .certs/acn_cosmos_11000.txt
is_abstract: false
---
public_id: valory/governatooorr_abci:0.1.0
type: skill
models:
  benchmark_tool:
    args:
      log_dir: /logs
  params:
    args:
      cleanup_history_depth: 1
      cleanup_history_depth_current: null
      drand_public_key: 868f005eb8e6e4ca0a47c8a77ceaa5309a47978a7c71bc5cce96366b5d7a569937c529eeda66c7293784a9402801af31
      finalize_timeout: 60.0
      genesis_config:
        genesis_time: '2022-09-26T00:00:00.000000000Z'
        chain_id: chain-c4daS1
        consensus_params:
          block:
            max_bytes: '22020096'
            max_gas: '-1'
            time_iota_ms: '1000'
          evidence:
            max_age_num_blocks: '100000'
            max_age_duration: '172800000000000'
            max_bytes: '1048576'
          validator:
            pub_key_types:
            - ed25519
          version: {}
        voting_power: '10'
      history_check_timeout: 1205
      init_fallback_gas: 0
      keeper_allowed_retries: 3
      keeper_timeout: 30.0
      max_attempts: 10
      max_healthcheck: 120
      multisend_address: ${str:0x0000000000000000000000000000000000000000}
      on_chain_service_id: ${int:null}
      reset_tendermint_after: ${int:2}
      retry_attempts: 400
      retry_timeout: 3
      reset_pause_duration: 10
      request_retry_delay: 1.0
      request_timeout: 10.0
      round_timeout_seconds: 30.0
      service_id: governatooorr
      service_registry_address: ${str:0x1cEe30D08943EB58EFF84DD1AB44a6ee6FEff63a}
      setup:
        all_participants: ${list:["0x10E867Ac2Fb0Aa156ca81eF440a5cdf373bE1AaC"]}
        safe_contract_address: ${str:0x0000000000000000000000000000000000000000}
        consensus_threshold: ${int:null}
      share_tm_config_on_startup: ${bool:false}
      sleep_time: 1
      tendermint_check_sleep_delay: 3
      tendermint_com_url: ${str:http://localhost:8080}
      tendermint_max_retries: 5
      tendermint_url: ${str:http://localhost:26657}
      tendermint_p2p_url: ${str:localhost:26656}
      termination_sleep: ${int:900}
      tx_timeout: 10.0
      use_termination: ${bool:false}
      tally_api_endpoint: ${str:https://api.tally.xyz/query}
      tally_api_key: ${str:<tally_api_key>}
      tally_api_call_sleep_seconds: ${int:2}
      snapshot_graphql_endpoint: ${str:https://hub.snapshot.org/graphql}
      snapshot_vote_endpoint: ${str:https://relayer.snapshot.org/}
      service_endpoint_base: ${str:https://governatooorr.staging.autonolas.tech/}
      validate_timeout: 1205
      voting_block_threshold: ${int:300}
      voting_seconds_threshold: ${int:10000}
      ceramic_api_base: ${str:https://ceramic-valory.hirenodes.io/}
      ceramic_api_create_endpoint: ${str:api/v0/streams}
      ceramic_api_commit_endpoint: ${str:api/v0/commits}
      ceramic_api_read_endpoint: ${str:api/v0/commits/{stream_id}}
      ceramic_did_seed: ${str:0101010101010101010101010101010101010101010101010101010101010101}
      ceramic_did_str: ${str:z6Mkon3Necd6NkkyfoGoHxid2znGc59LU3K7mubaRcFbLfLX}
      default_read_stream_id: ${str:kjzl6cwe1jw149erp7y8pg1kwk0103714knt33k66rkdrwn1zmskykj8ho8y15n}
      ceramic_stream_id: ${str:kjzl6cwe1jw149erp7y8pg1kwk0103714knt33k66rkdrwn1zmskykj8ho8y15n}
      default_read_target_property: ${str:ceramic_db}
      signmessagelib_address: ${str:0xA65387F16B013cf2Af4605Ad8aA5ec25a2cbA3a2}
---
public_id: fetchai/http_server:0.22.0:bafybeicblltx7ha3ulthg7bzfccuqqyjmihhrvfeztlgrlcoxhr7kf6nbq
type: connection
config:
  host: 0.0.0.0
  target_skill_id: valory/governatooorr_abci:0.1.0
